// <auto-generated />
using System;
using CompanyEmployees.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompanyEmployees.WebApi.Migrations
{
    [DbContext(typeof(CompanyEmployeeDbContext))]
    partial class CompanyEmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyEmployees.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a627d731-5382-4bf4-87c0-4f256fddd004"),
                            Address = "Marib street, Al-akwa3 building",
                            Country = "Yemen",
                            Name = "Ebda3Soft"
                        },
                        new
                        {
                            Id = new Guid("73625b4e-4149-4912-b6d9-08a595d78124"),
                            Address = "50 street, YemenSoft building",
                            Country = "Yemen",
                            Name = "YemenSoft"
                        },
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Address = "583 Wall Dr. Gwynn Oak, MD 21207",
                            Country = "USA",
                            Name = "IT_Solutions Ltd"
                        },
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Address = "312 Forest Avenue, BF 923",
                            Country = "USA",
                            Name = "Admin_Solutions Ltd"
                        });
                });

            modelBuilder.Entity("CompanyEmployees.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffa02d9a-37d9-4565-9f2f-bfd079666116"),
                            Age = 30,
                            CompanyId = new Guid("a627d731-5382-4bf4-87c0-4f256fddd004"),
                            Name = "Khaled Ali",
                            Password = "$2a$11$1K4G1I.HyDkBQcP7tZ.7i.Nn882IzqKPUnrOUHfUjMVOL271kR6je",
                            Position = "Software developer",
                            Role = "admin",
                            UserName = "khalid-ali"
                        },
                        new
                        {
                            Id = new Guid("b222cc38-2ecb-4314-88e9-2c8a7ce4a554"),
                            Age = 24,
                            CompanyId = new Guid("a627d731-5382-4bf4-87c0-4f256fddd004"),
                            Name = "Mohammed Al-Batool",
                            Password = "$2a$11$3m7MnU62UyYW/5btVU61xeM3Gm84I7bdtoubWxYhcU8I2BScyFu4.",
                            Position = "Mobile developer",
                            Role = "employee",
                            UserName = "Mohammed"
                        },
                        new
                        {
                            Id = new Guid("fc61c65c-1861-4d0d-b091-8c85a2c21171"),
                            Age = 24,
                            CompanyId = new Guid("a627d731-5382-4bf4-87c0-4f256fddd004"),
                            Name = "Osamah Al-Obary",
                            Password = "$2a$11$PWhbSGO4AnAZNHNcCElMZuFsu/jrhdI2/imBXQEYk6ce5jonZ3n3i",
                            Position = "Software developer",
                            Role = "employee",
                            UserName = "Osamah"
                        },
                        new
                        {
                            Id = new Guid("babb5dff-d056-4620-a14c-4acc2f421af6"),
                            Age = 26,
                            CompanyId = new Guid("a627d731-5382-4bf4-87c0-4f256fddd004"),
                            Name = "Ahmed Al-Hemuary",
                            Password = "$2a$11$xqwTYTJJ88p9mP5teQs2lei/ZoBYbH/fDOaD/ycD1wCk/OX73UUlu",
                            Position = "Tester",
                            Role = "employee",
                            UserName = "Ahmed"
                        },
                        new
                        {
                            Id = new Guid("a4ff3237-13c3-4ee1-9f8b-57d2e38b997a"),
                            Age = 32,
                            CompanyId = new Guid("73625b4e-4149-4912-b6d9-08a595d78124"),
                            Name = "Osamah Salam",
                            Password = "$2a$11$/54euhp75LFjMtjE2EUqQOGiFiWjJyMT.PbuO8FEWvSVPZLIdo1sW",
                            Position = "Customer service",
                            Role = "employee",
                            UserName = "Salam"
                        },
                        new
                        {
                            Id = new Guid("7cce86d2-ee60-4de9-a098-ab8e45cce73a"),
                            Age = 26,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Sam Raiden",
                            Password = "$2a$11$h8cbfBNBSkjf47OTekNfreTvaoqMddLYgFUuOkdzA1lCe91kYWTsi",
                            Position = "Accounting",
                            Role = "employee",
                            UserName = "Sam"
                        },
                        new
                        {
                            Id = new Guid("ae6dff3c-abf4-4d79-a74e-3e14648db2f5"),
                            Age = 30,
                            CompanyId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Name = "Jana McLeaf",
                            Password = "$2a$11$GGbwZquAYZQ9Jnhhct.pD.J/jVTzMRBbMYsgvUdmzRVGGPv6Bzyla",
                            Position = "Marketing ",
                            Role = "employee",
                            UserName = "Jana"
                        },
                        new
                        {
                            Id = new Guid("50c1aed5-a50a-4f64-9533-910e68c30206"),
                            Age = 35,
                            CompanyId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Name = "Kane Miller",
                            Password = "$2a$11$CWzFaNhz0GIMCiQOaanm3e5rEn6G/zxrvRI29NzqtdS3bHNkuUA6a",
                            Position = "Adminstrater",
                            Role = "employee",
                            UserName = "Kane"
                        });
                });

            modelBuilder.Entity("CompanyEmployees.Domain.Employees.Employee", b =>
                {
                    b.HasOne("CompanyEmployees.Domain.Companies.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CompanyEmployees.Domain.Companies.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
